export const BUY_MOBILE = "BUY_MOBILE";
export const BUY_LAPTOP = "BUY_LAPTOP";
export const FETCH_REQUEST_SUCCESS = "FETCH_REQUEST_SUCCESS";
export const FETCH_REQUEST_FAIL = "FETCH_REQUEST_FAIL";
export const FETCH_USERS_REQUEST = "FETCH_USERS_REQUEST";
